image: openjdk:11-jdk

stages:
  - build
  - publish
  - deploy

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:gradle:
  stage: build
  only:
    - tags
  tags: 
    - comsc-ci
    
  script:
    - ./gradlew buildAndReport
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - ./build/reports/tests/
      - ./build/reports/checkstyle/
      - ./build/jacocoHtml
      - ./build/libs/*.jar
    expire_in: 1 week


            - mkdir .public
            - cd .public
            - echo "<HTML><HEAD></HEAD><BODY><H1>Latest Test Report</H1><DIV><A href=http://"$GITLAB_USER_LOGIN".pages.cs.cf.ac.uk/"$CI_PROJECT_NAME"/tests/test/>Results</A></DIV></BODY></HTML>" > index.html
            - cd ..
            - cp -r ./build/reports/tests/ .public
            - mv .public public
            - ls -lR ./public


pages:

  stage: publish
  tags: 
    - comsc-ci



  script:
    - pwd
    - mkdir .public
    - cd .public
    - mkdir jars
    - echo "<HTML><HEAD></HEAD><BODY><H1>Latest Test Report</H1><DIV><A href=http://"$GITLAB_USER_LOGIN".pages.cs.cf.ac.uk/"$CI_PROJECT_NAME"/tests/test/>Results</A></DIV></BODY></HTML>" > index.html
    - cd ..
  
    - cp -r ./build/reports/tests/ .public
    - cp -r ./build/reports/checkstyle/ .public
    - cp -r ./build/jacocoHtml/ .public
    - cp -r ./build/libs/*.jar .public/jars
    - mv .public public
    - pwd
    - ls -lR public



  artifacts:
    paths:
      - public

  only:
    - tags
